name: bookmark-cd
base: core20
version: '0.2.4'
summary: bcd is a way to cd to directories that have been bookmarked.
description: |
  bcd is a way to cd to directories that have been bookmarked.

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

plugs:
  dot-bashrc:
    interface: personal-files
    write:
      - $HOME/.bashrc

parts:
  bookmark-cd:
    plugin: rust
    source: .

apps:
  bookmark-cd:
    command: bin/bookmark-cd

