---
name: CI Build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build:
    name: "CI Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        RUST: [stable]
        TARGET:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
        include:
          - TARGET: [x86_64-apple-darwin, aarch64-apple-darwin]
            MACOS: true

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Rust Toolchain setup"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.RUST }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: "MacOS toolchain"
        uses: mbround18/setup-osxcross@v1
        with:
          osx-version: "12.3"
        if: ${{ matrix.MACOS }}

      - name: "Build"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }}
